version: '3.8'

services:
  calendar-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar_agent_app
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      - APP_MODULE=main:app
    volumes:
      # Mount your main application code read-write
      - ./app:/usr/src/app
      # Explicitly mount config.json from host
      - ./config.json:/usr/src/app/config.json
      # Mount credentials read-write (as before)
      - ./.credentials:/usr/src/app/.credentials:rw
      # Optional: Mount mcp_server code if you need to develop it live
      # This would now mount OVER the built one if enabled, be careful
      # - ./mcp_server:/usr/src/mcp_server:ro
    restart: unless-stopped
    # Command to run the application (reload flags disabled)
    command: uvicorn main:app --host 0.0.0.0 --port 3001